config/routes.rb
Rails.application.routes.draw do

  resources :specialization_weights
  resources :skill_levels
  resources :specialization_skills
  resources :specialization_categories

  resources :skills
  resources :positions
  resources :users
  resources :areas
  resources :profiles
  resources :skill_categories
  resources :specializations
  resources :levels
  resources :position_skills
  root 'dashboard#index'

end

app/models/skill_category.rb
class SkillCategory < ActiveRecord::Base

  has_many :skills
  has_many :specialization_weights

  validates :name, presence: true, allow_blank: false, length: { minimum: 5 }

end

app/controllers/skill_categories_controller.rb
class SkillCategoriesController < ApplicationController
  before_action :set_skill_cat, only: [:show, :edit, :update, :destroy]

  # GET /skill_cats
  # GET /skill_cats.json
  def index
    @skill_cats = SkillCategory.all
  end

  # GET /skill_cats/1
  # GET /skill_cats/1.json
  def show
  end

  # GET /skill_cats/new
  def new
    @skill_cat = SkillCategory.new
  end

  # GET /skill_cats/1/edit
  def edit
  end

  # POST /skill_cats
  # POST /skill_cats.json
  def create
    @skill_cat = SkillCategory.new(skill_cat_params)

    respond_to do |format|
      if @skill_cat.save
        format.html { redirect_to @skill_cat, notice: 'Skill cat was successfully created.' }
        format.json { render :show, status: :created, location: @skill_cat }
      else
        format.html { render :new }
        format.json { render json: @skill_cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skill_cats/1
  # PATCH/PUT /skill_cats/1.json
  def update
    respond_to do |format|
      if @skill_cat.update(skill_cat_params)
        format.html { redirect_to @skill_cat, notice: 'Skill cat was successfully updated.' }
        format.json { render :show, status: :ok, location: @skill_cat }
      else
        format.html { render :edit }
        format.json { render json: @skill_cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skill_cats/1
  # DELETE /skill_cats/1.json
  def destroy
    @skill_cat.destroy
    respond_to do |format|
      format.html { redirect_to skill_categories_url, notice: 'Skill cat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill_cat
      @skill_cat = SkillCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def skill_cat_params
      params.require(:skill_category).permit(:name)
    end
end

app/helpers/skill_categories_helper.rb
module SkillCategoriesHelper
end

app/views/skill_categories/_form.html.erb
<%= form_for(@skill_cat) do |f| %>
  <% if @skill_cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@skill_cat.errors.count, "error") %> prohibited this skill_cat from being saved:</h2>

      <ul>
      <% @skill_cat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :name %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/skill_categories/edit.html.erb
<h1>Editing skill_cat</h1>

<%= render 'form' %>

<%= link_to 'Show', @skill_cat %> |
<%= link_to 'Back', skill_categories_path %>

app/views/skill_categories/index.html.erb
<h1>Listing skill_cats</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @skill_cats.each do |skill_cat| %>
      <tr>
        <td> <%= skill_cat.name %>
        </td>  
        <td><%= link_to 'Show', skill_cat %></td>
        <td><%= link_to 'Edit', edit_skill_category_path(skill_cat) %></td>
        <td><%= link_to 'Destroy', skill_cat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Skill cat', new_skill_category_path %>

app/views/skill_categories/new.html.erb
<h1>New skill_cat</h1>

<%= render 'form' %>

<%= link_to 'Back', skill_categories_path %>

app/views/skill_categories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_skill_category_path(@skill_cat) %> |
<%= link_to 'Back', skill_categories_path %>