config/routes.rb
Rails.application.routes.draw do

  resources :specialization_weights
  resources :skill_levels
  resources :specialization_skills
  resources :specialization_categories

  resources :skills
  resources :positions
  resources :users
  resources :areas
  resources :profiles
  resources :skill_categories
  resources :specializations
  resources :levels
  resources :position_skills
  root 'dashboard#index'

end

app/models/specialization_skill.rb
class SpecializationSkill < ActiveRecord::Base

  belongs_to :skill
  belongs_to :specialization
  
  validates :specialization, presence: true
  validates :skill, presence: true

end

app/controllers/specialization_skills_controller.rb
class SpecializationSkillsController < ApplicationController
  before_action :set_specialization_skill, only: [:show, :edit, :update, :destroy]

  # GET /specialization_skills
  # GET /specialization_skills.json
  def index
    @specialization_skills = SpecializationSkill.all
  end

  # GET /specialization_skills/1
  # GET /specialization_skills/1.json
  def show
  end

  # GET /specialization_skills/new
  def new
    @specialization_skill = SpecializationSkill.new
  end

  # GET /specialization_skills/1/edit
  def edit
  end

  # POST /specialization_skills
  # POST /specialization_skills.json
  def create
    @specialization_skill = SpecializationSkill.new(specialization_skill_params)

    respond_to do |format|
      if @specialization_skill.save
        format.html { redirect_to @specialization_skill, notice: 'Specialization skill was successfully created.' }
        format.json { render :show, status: :created, location: @specialization_skill }
      else
        format.html { render :new }
        format.json { render json: @specialization_skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /specialization_skills/1
  # PATCH/PUT /specialization_skills/1.json
  def update
    respond_to do |format|
      if @specialization_skill.update(specialization_skill_params)
        format.html { redirect_to @specialization_skill, notice: 'Specialization skill was successfully updated.' }
        format.json { render :show, status: :ok, location: @specialization_skill }
      else
        format.html { render :edit }
        format.json { render json: @specialization_skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specialization_skills/1
  # DELETE /specialization_skills/1.json
  def destroy
    @specialization_skill.destroy
    respond_to do |format|
      format.html { redirect_to specialization_skills_url, notice: 'Specialization skill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_specialization_skill
      @specialization_skill = SpecializationSkill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def specialization_skill_params
      params.require(:specialization_skill).permit(:specialization_id, :skill_id)
    end
end

app/helpers/specialization_skills_helper.rb
module SpecializationSkillsHelper
end

app/views/specialization_skills/_form.html.erb
<%= form_for(@specialization_skill) do |f| %>
  <% if @specialization_skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@specialization_skill.errors.count, "error") %> prohibited this specialization_skill from being saved:</h2>

      <ul>
      <% @specialization_skill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/specialization_skills/edit.html.erb
<h1>Editing specialization_skill</h1>

<%= render 'form' %>

<%= link_to 'Show', @specialization_skill %> |
<%= link_to 'Back', specialization_skills_path %>

app/views/specialization_skills/index.html.erb
<h1>Listing specialization_skills</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @specialization_skills.each do |specialization_skill| %>
      <tr>
        <td><%= link_to 'Show', specialization_skill %></td>
        <td><%= link_to 'Edit', edit_specialization_skill_path(specialization_skill) %></td>
        <td><%= link_to 'Destroy', specialization_skill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Specialization skill', new_specialization_skill_path %>

app/views/specialization_skills/new.html.erb
<h1>New specialization_skill</h1>

<%= render 'form' %>

<%= link_to 'Back', specialization_skills_path %>

app/views/specialization_skills/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_specialization_skill_path(@specialization_skill) %> |
<%= link_to 'Back', specialization_skills_path %>